"""Add a generated United Kingdom boundary for Valhalla's admin database.

Valhalla decides which side of the road traffic drives on from closed country
boundaries. Clipping cuts the real ones, so we give it a rectangle around the
region tagged as the UK instead (see docs/decisions.md).

The boundary is merged into the filtered extract rather than kept as a second
file: Valhalla's tile builder needs a single input sorted by id, and aborts with
"Detected unsorted input data" when given two files.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import osmium
from osmium.osm.mutable import Node, Relation, Way

from spirited.extract.clip import osmium_exe
from spirited.region import CLIP_BOX, BBox, Paths

# Margin around the clip box, in degrees, so every road sits well inside.
MARGIN = 0.1

UK_TAGS = {
    "type": "boundary",
    "boundary": "administrative",
    "admin_level": "2",
    "name": "United Kingdom",
    "ISO3166-1": "GB",
    "ISO3166-1:alpha2": "GB",
    "note": "Generated by Spirited; not the real boundary",
}

# Far above any real OSM id (about 1.3e10 for nodes in 2026), so they cannot clash
# and they sort after every real object, which keeps the merged file in order.
ID_BASE = 10**12
WAY_ID = ID_BASE + 1
RELATION_ID = ID_BASE + 1


def boundary_corners(box: BBox = CLIP_BOX) -> list[tuple[float, float]]:
    """(lon, lat) corners of the boundary, anticlockwise from the south-west."""
    west, south = box.min_lon - MARGIN, box.min_lat - MARGIN
    east, north = box.max_lon + MARGIN, box.max_lat + MARGIN
    return [(west, south), (east, south), (east, north), (west, north)]


def write_admin_boundary(path: Path, box: BBox = CLIP_BOX) -> None:
    corners = boundary_corners(box)
    node_ids = [ID_BASE + i + 1 for i in range(len(corners))]
    writer = osmium.SimpleWriter(str(path), overwrite=True)
    try:
        for node_id, (lon, lat) in zip(node_ids, corners, strict=True):
            writer.add_node(Node(id=node_id, version=1, location=(lon, lat)))
        writer.add_way(Way(id=WAY_ID, version=1, nodes=[*node_ids, node_ids[0]]))
        writer.add_relation(
            Relation(id=RELATION_ID, version=1, members=[("w", WAY_ID, "outer")], tags=UK_TAGS)
        )
    finally:
        writer.close()


def add_admin_boundary(paths: Paths, box: BBox = CLIP_BOX) -> None:
    """Merge the generated boundary into the filtered extract, in place."""
    write_admin_boundary(paths.admin, box)
    merged = paths.filtered.with_name("region-filtered.merging.osm.pbf")
    subprocess.run(
        [
            osmium_exe(),
            "merge",
            str(paths.filtered),
            str(paths.admin),
            "-o",
            str(merged),
            "--overwrite",
        ],
        check=True,
    )
    merged.replace(paths.filtered)
