"""Write a generated United Kingdom boundary for Valhalla's admin database.

Valhalla decides which side of the road traffic drives on from closed country
boundaries. Clipping cuts the real ones, so we give it a rectangle around the
region tagged as the UK instead (see docs/decisions.md).
"""

from __future__ import annotations

from pathlib import Path

import osmium
from osmium.osm.mutable import Node, Relation, Way

from spirited.region import CLIP_BOX, BBox

# Margin around the clip box, in degrees, so every road sits well inside.
MARGIN = 0.1

UK_TAGS = {
    "type": "boundary",
    "boundary": "administrative",
    "admin_level": "2",
    "name": "United Kingdom",
    "ISO3166-1": "GB",
    "ISO3166-1:alpha2": "GB",
    "note": "Generated by Spirited; not the real boundary",
}

# Negative ids cannot clash with real OSM objects.
WAY_ID = -1
RELATION_ID = -1


def boundary_corners(box: BBox = CLIP_BOX) -> list[tuple[float, float]]:
    """(lon, lat) corners of the boundary, anticlockwise from the south-west."""
    west, south = box.min_lon - MARGIN, box.min_lat - MARGIN
    east, north = box.max_lon + MARGIN, box.max_lat + MARGIN
    return [(west, south), (east, south), (east, north), (west, north)]


def write_admin_boundary(path: Path, box: BBox = CLIP_BOX) -> None:
    corners = boundary_corners(box)
    node_ids = [-(i + 1) for i in range(len(corners))]
    writer = osmium.SimpleWriter(str(path), overwrite=True)
    try:
        for node_id, (lon, lat) in zip(node_ids, corners, strict=True):
            writer.add_node(Node(id=node_id, version=1, location=(lon, lat)))
        writer.add_way(Way(id=WAY_ID, version=1, nodes=[*node_ids, node_ids[0]]))
        writer.add_relation(
            Relation(id=RELATION_ID, version=1, members=[("w", WAY_ID, "outer")], tags=UK_TAGS)
        )
    finally:
        writer.close()
